### ISSUE TITLE
How to install requirements?

### ISSUE THREAD

**Issue by robmarkcole** [jroes/streamlit-getting-started-m1#1]
Many thanks for creating this, I have generally avoided using conda but it appears to be a requirement here. Can you advise how the line in devcontainer `// "postCreateCommand": "pip3 install --user -r requirements.txt",` should be ammended?

**Comment by jroes** [comment]
So glad that it's helpful!

I'm not a conda expert myself, either. [This](https://stackoverflow.com/questions/51042589/conda-version-pip-install-r-requirements-txt-target-lib/51043636) seems to indicate you could use `conda install --file requirements.txt`, do you think that might work?

**Comment by robmarkcole** [comment]
Ok it appears to be the solution!
