### ISSUE TITLE
ModuleNotFoundError: No module named 'altair.vegalite.v4'

### ISSUE THREAD

**Issue by msealander** [jroes/streamlit-getting-started-m1#2]
This is awesome, but it is now generating this error when you try to open streamlit after building the container: 
https://discuss.streamlit.io/t/modulenotfounderror-no-module-named-altair-vegalite-v4/42921

**Comment by jroes** [comment]
Hmm, I haven’t used this repo in a while, but I’m not getting this issue from a fresh run through of the README. Any more info you can share about what you’re running?

**Comment by msealander** [comment]
So weird, tried again with a fresh clone and build and streamlit starts no problem. Thanks and sorry...

**Comment by jroes** [comment]
No worries. Glad this thing still works!
